package com.logistics;

import com.logistics.pages.DashboardPage;
import com.logistics.pages.LoginPage;
import com.logistics.pages.ProductPage;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AdminUiFlowTest extends BaseTest {

    @Test
    void testAdminUiFlow() {
        LoginPage loginPage = new LoginPage(driver, wait);
        DashboardPage dashboardPage = new DashboardPage(driver, wait);
        ProductPage productPage = new ProductPage(driver, wait);

        // 1. Admin login
        System.out.println("Navigating to login page...");
        loginPage.navigateTo(baseUrl);
        System.out.println("Submitting credentials...");
        loginPage.login("admin", "Admin@123");

        // Verify successful login by checking for the brand logo or sidebar
        System.out.println("Verifying login success...");
        WebElement sidebarBrand = wait.until(ExpectedConditions.visibilityOfElementLocated(By.className("sidebar-logo-text")));
        assertTrue(sidebarBrand.getText().contains("LogisticsHub"), "Login failed or logo not found!");

        // 2. Sidebar Navigation: Navigate to Products
        System.out.println("Navigating to Products page via sidebar...");
        dashboardPage.navigateToProducts();
        assertTrue(dashboardPage.getPageTitleText().equalsIgnoreCase("Products"), "Navigation to Products page failed!");

        // 3. Product Add Flow
        System.out.println("Opening Add Product form...");
        productPage.clickAddProductButton();
        
        String randomSku = "AUTO-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
        String productName = "Selenium Test Item " + randomSku;
        
        System.out.println("Creating new product with SKU: " + randomSku);
        productPage.createNewProduct(
                randomSku,
                productName,
                "Automated product description generated by Selenium test runner.",
                "150.00",
                "249.99",
                "75",
                "1", // Category ID 1 (Electronics)
                "",  // Warehouse ID optional
                "350", // Weight in grams
                "HIGH" // Importance select value
        );

        // Verify product was added successfully (redirects back to listing)
        System.out.println("Verifying product listing update...");
        WebElement toastMessage = wait.until(ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//div[contains(@class, 'Toastify__toast-body') and contains(., 'created')]")
        ));
        String toastText = toastMessage.getText();
        System.out.println("Toast message text: " + toastText);
        assertTrue(toastText.toLowerCase().contains("created"), "Success toast message not displayed! Actual text: " + toastText);

        // 4. Sidebar Navigation: Navigate to AI Forecast Dashboard
        System.out.println("Navigating to AI Forecast Dashboard...");
        dashboardPage.navigateToAiForecast();
        assertTrue(dashboardPage.getPageTitleText().contains("Forecast"), "Navigation to AI Forecast page failed!");
        
        // 5. Sidebar Navigation: Navigate to Damage Detection Page
        System.out.println("Navigating to Damage Detection Page...");
        dashboardPage.navigateToDamageDetection();
        assertTrue(dashboardPage.getPageTitleText().contains("Damage"), "Navigation to Damage Detection page failed!");
        
        System.out.println("Admin UI automation flow completed successfully!");
    }
}
